# Generated by Django 4.2.5 on 2023-09-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('CModel', models.CharField(max_length=200)),
            ],
        ),
    ]
